#ifndef _IMAGEFORMAT_H_
#define _IMAGEFORMAT_H_

#define IMAGEFORMAT CAIRO_FORMAT_RGB24
#define IMAGEWIDTH 625
#define IMAGEHEIGHT 625
#define PNGVIEWER_MAX_VIEWS_ROWS 1
#define PNGVIEWER_MAX_VIEWS_COLUMNS 2

#endif
